--- a/Makefile.am
+++ b/Makefile.am
@@ -11,7 +11,7 @@
 	tools/CHARMM/gen_structure tools/CHARMM/gen_input \
 	tools/refs_converge tools/refs_converge_py3
 
-dist_pkglibexec_SCRIPTS = vmdplugins/libexec/*.so
+dist_pkglibexec_SCRIPTS = vmdplugins/compile/*.so
 
 ersources = enganal.F90 engmain.F90 realcal.F90 spline.F90 fft_iface.F90 mpiproc.F90 engproc.F90 recpcal.F90 insertion.F90 setconf.F90 trajectory.F90 utility.F90 bestfit.F90
 
--- a/Makefile.in
+++ b/Makefile.in
@@ -367,7 +367,7 @@
 	tools/CHARMM/gen_structure tools/CHARMM/gen_input \
 	tools/refs_converge tools/refs_converge_py3
 
-dist_pkglibexec_SCRIPTS = vmdplugins/libexec/*.so
+dist_pkglibexec_SCRIPTS = vmdplugins/compile/*.so
 ersources = enganal.F90 engmain.F90 realcal.F90 spline.F90 fft_iface.F90 mpiproc.F90 engproc.F90 recpcal.F90 insertion.F90 setconf.F90 trajectory.F90 utility.F90 bestfit.F90
 EXTRA_DIST = parameters_er.example parameters_fe.example extensions/* \
 	trajectory-formats/* tools/AMBER/* tools/gromacs/* \
