--- a/Makefile.am
+++ b/Makefile.am
@@ -9,7 +9,7 @@
 	tools/LAMMPS/gen_structure tools/LAMMPS/gen_input \
 	tools/CHARMM/gen_structure tools/CHARMM/gen_input
 
-dist_pkglibexec_SCRIPTS = vmdplugins/libexec/*.so
+dist_pkglibexec_SCRIPTS = vmdplugins/compile/*.so
 
 ersources = enganal.F90 engmain.F90 realcal.F90 spline.F90 fft_iface.F90 mpiproc.F90 engproc.F90 recpcal.F90 insertion.F90 setconf.F90 trajectory.F90 utility.F90 bestfit.F90
 
--- a/Makefile.in
+++ b/Makefile.in
@@ -247,7 +247,7 @@
 	tools/LAMMPS/gen_structure tools/LAMMPS/gen_input \
 	tools/CHARMM/gen_structure tools/CHARMM/gen_input
 
-dist_pkglibexec_SCRIPTS = vmdplugins/libexec/*.so
+dist_pkglibexec_SCRIPTS = vmdplugins/compile/*.so
 ersources = enganal.F90 engmain.F90 realcal.F90 spline.F90 fft_iface.F90 mpiproc.F90 engproc.F90 recpcal.F90 insertion.F90 setconf.F90 trajectory.F90 utility.F90 bestfit.F90
 EXTRA_DIST = parameters_er.example parameters_fe.example extensions/* \
 	trajectory-formats/* tools/NAMD/* tools/gromacs/* \
